### ISSUE TITLE
will this work with nextjs and razzlejs

### ISSUE THREAD

**Issue by laurencefass** [maapteh/react-no-ssr#37]
I'm very impressed by the simplicity of this compared to dynamic module load alternatives to ive been looking at top achieve something similar. 

will it "just work" with any SSR libraries like Next.js and Razzle.js? 

thanks

**Comment by maapteh** [comment]
Hi, yes it will work with any library using React. For nextjs they use hook for example see https://github.com/zeit/next.js/blob/8b01a34b6025e4c6ed004ca8e9111428dd3d9d99/examples/progressive-render/pages/index.js but i decided to create a re-usable component for it. It depends how you will use it, for example with GraphQL you can simply pass ssr: true/false to the query which will make it ssr or not then you will not need it. I created another component which will start showing the inner component when it comes into view, in some cases that's even nicer!

**Comment by maapteh** [comment]
the other component `import InView from '@mpth/react-in-view';` can be found working in code: 
https://github.com/maapteh/graphql-modules-app/blob/master/packages/app/src/pages/lazy.js
 and on heroku https://graphql-schiphol.herokuapp.com/lazy (needs time to spin up, instances are scaled down when no load, so be patient first time)

**Comment by maapteh** [comment]
If you want lazy modules, then be careful. Because real lazy modules will be split from your main bundle, so your bundle becomes much cleaner. This module will still compile all needed code, so mostly used on component level.
